import './style.css'
import './ts-basics-1-1/basic'
import './ts-intro-1-8/intro-1-8'
import './ts-intro-1-13/intro-1-13'
import './ts-intro-1-16/intro-1-16'
import './string-number-dom/string-number-dom'
import './string-number-dom/dom'
import './conditionals-math-date/math'
import './conditionals-math-date/conditionals'
import './conditionals-uebungen/conditionals-uebungen'
import './date-uebungen/date'
import './math-uebungen/math'
import './functions/functions'
import './functions-uebungen/functions-uebungen'
import './arrays/arrays'
import './arrys-uebungen/arrays-uebungen'
import './array-todolist/todolist'
import './wheelofnames/wheelofnames'
import './array-uebungen-II/array-uebungen-II'
import './array-search/array-serach'
import './map-foreach/map-foreach'
import './map-foreach-uebungen/map-foreach-uebungen'
import './loops/loops'
import './loops-uebungen/loops-uebungen'
import './loops-uebungen-II/loops-uebungen-II'
import './objects/objects'

// import garnicht nötig? Sonst lädt alles sofort in der Main Index.html